### ISSUE TITLE
cannot get the frame content.

### ISSUE THREAD

**Issue by pswiatki** [PW-Sat2/HAMRadio#7]
When clicking on UUID link the demodulator pane there is no reaction and the following can be seen in the DEBUG traces:

```
/usr/lib/chromium/chromium: relocation error: /usr/lib/chromium/chromium: symbol jpeg_crop_scanline version LIBJPEG_8.0 not defined in file libjpeg.so.8 with link time reference
/usr/bin/xdg-open: line 881: x-www-browser: command not found
/usr/bin/xdg-open: line 881: firefox: command not found
/usr/bin/xdg-open: line 881: iceweasel: command not found
/usr/bin/xdg-open: line 881: seamonkey: command not found
/usr/bin/xdg-open: line 881: mozilla: command not found
/usr/bin/xdg-open: line 881: epiphany: command not found
/usr/bin/xdg-open: line 881: konqueror: command not found
/usr/lib/chromium/chromium: relocation error: /usr/lib/chromium/chromium: symbol jpeg_crop_scanline version LIBJPEG_8.0 not defined in file libjpeg.so.8 with link time reference
/usr/bin/xdg-open: line 881: chromium-browser: command not found
/usr/bin/xdg-open: line 881: google-chrome: command not found
/usr/bin/xdg-open: line 881: www-browser: command not found
/usr/bin/xdg-open: line 881: links2: command not found
/usr/bin/xdg-open: line 881: elinks: command not found
/usr/bin/xdg-open: line 881: links: command not found
/usr/bin/xdg-open: line 881: lynx: command not found
/usr/bin/xdg-open: line 881: w3m: command not found
xdg-open: no method available for opening 'http://radio.pw-sat.pl/communication/frame/6681ef6c-52da-4e47-a358-a304040a68fb'
```
What could be the problem here?

**Comment by begreeen** [comment]
Hi @pswiatki,
The reason is that the app is ~freezed~ frozen by pyinstaller on Ubuntu 16.04 LTS. It includes lots of system libraries and sometimes version of those ~'freezed'~ `frozen` (included) libraries are not compatible with other libraries in your system.

**As a workaround**: try to remove (or rename at first try) `libjpeg.so.8` from `<path_to_pw-sat2-gs>/main` directory and run application again. Then this lib should be loaded from your system.

Sorry for that, I know that this method of providing the app is not perfect, but it was the only feasible one.

**Comment by pswiatki** [comment]
I see.... yes, I was actually curious about that statement in the wiki (please, correct in the WIKI text):
**"frozen"**. Checking if it will pick up the proper lib... Will keep you posted.

**Comment by pswiatki** [comment]
After renaming **`libjpeg.so.8`** the functionality started working. Thanks for you advice.

**Comment by pswiatki** [comment]
Did not take into account the fact that the app came with its own set of "frozen" libraries. After follwing the advice provided by @begreeen it started working properly.
